parameters:
- name: backendAzureRmContainerName
- name: environmentServiceName
- name: backendAzureRmResourceGroupName
- name: backendAzureRmResourceGroupLocation
- name: backendAzureRmStorageAccountName
- name: backendAzureRmKey
  default: 'terraform.tfstate'
- name: planCommandOptions

jobs:
- template: PipelineTemplates/Jobs/Terraform/terraform-apply-job.yml@templates
  parameters:
    name: 'AccessTokenFunctionapp'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Infrastructure/Terraform'
    backendAzureRmContainerName: ${{ parameters.backendAzureRmContainerName }}
    environmentServiceName: ${{ parameters.environmentServiceName }}
    backendAzureRmResourceGroupName: ${{ parameters.backendAzureRmResourceGroupName }}
    backendAzureRmResourceGroupLocation: ${{ parameters.backendAzureRmResourceGroupLocation }}
    backendAzureRmStorageAccountName: ${{ parameters.backendAzureRmStorageAccountName }}
    backendAzureRmKey: ${{ parameters.backendAzureRmKey }}
    planCommandOptions: ${{ parameters.planCommandOptions }}


