trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      name: tumsky12/SharedInfrastructure
      endpoint: GitHubConnection
      ref:  'refs/heads/feature/terraform-pipeline-changes'

variables:
- group: shared-variable-group

jobs:
# - job: foo
#   steps:
#   - script: echo $(environmentServiceName)
#   - script: echo $(devBackendAzureRmResourceGroupName)
#   - script: echo $(devBackendAzureRmStorageAccountName)
#   - script: echo $(devBackendAzureRmKey)

- template: apply-function-app-infrastructure-template.yml
  parameters:
    backendAzureRmContainerName: 'pat-tf-storage'
    environmentServiceName: $(environmentServiceName)
    backendAzureRmResourceGroupName: 'terraform-dev'
    backendAzureRmStorageAccountName: 'terraformdev8716912495'
    backendAzureRmKey: 'terraform-dev'
    planCommandOptions: '-var-file="Variables/dev.tfvars" -var "devops_organization_name=$(organizationName)"'

