trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      name: tumsky12/SharedInfrastructure
      endpoint: GitHubConnection

stages:
- template: destroy-function-app-infrastructure-template.yml
