trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      name: tumsky12/SharedInfrastructure
      endpoint: GitHubConnection
      ref:  'refs/heads/terraform-pipelines-changes'

variables:
- group: shared-variable-group

jobs:
- template: destroy-function-app-infrastructure-template.yml
  parameters:
    backendAzureRmResourceGroupName: $(devBackendAzureRmResourceGroupName)
    backendAzureRmStorageAccountName: $(devBackendAzureRmStorageAccountName)
    tfVarsFile: dev.tfvars