trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      name: tumsky12/CorePipelineTemplates
      endpoint: GitHubConnection
      ref:  'refs/heads/feature/terraform-pipeline-changes'
    - repository: terraformModules
      type: github
      name: tumsky12/CoreTerraformModules
      endpoint: GitHubConnection
      ref:  'refs/heads/feature/terraform-pipeline-changes'

variables:
- group: shared-variable-group

jobs:
- template: destroy-function-app-infrastructure-template.yml
  parameters:
    backendAzureRmResourceGroupName: $(devBackendAzureRmResourceGroupName)
    backendAzureRmStorageAccountName: $(devBackendAzureRmStorageAccountName)
    tfVarsFile: dev.tfvars