parameters:
- name: backendAzureRmResourceGroupName
- name: backendAzureRmStorageAccountName
- name: tfVarsFile

jobs:
- template: Templates/Jobs/Terraform/terraform-destroy-job.yml@templates
  parameters:
    name: 'AccessTokenFunctionApp'
    workingDirectory: $(System.DefaultWorkingDirectory)/RenewDevopsPAT/Infrastructure/Terraform
    environmentServiceName: $(environmentServiceName)
    backendAzureRmResourceGroupName: ${{ parameters.backendAzureRmResourceGroupName }}
    backendAzureRmResourceGroupLocation: $(backendAzureRmResourceGroupLocation)
    backendAzureRmStorageAccountName: ${{ parameters.backendAzureRmStorageAccountName }}
    backendAzureRmContainerName: 'pat-tf-storage'
    planCommandOptions: '-var-file="Variables/${{ parameters.tfVarsFile }}" -var="devops_organization_name=$(organizationName)"'
